const mongoose = require("mongoose");
const path = require("path")
require("dotenv").config({ path: path.join(__dirname, "../.env") })
const Tour = require("../models/Tour.js"); // Đảm bảo đường dẫn đúng


// Hàm tạo ID ngẫu nhiên
const generateTourId = () => "TOUR" + Date.now() + Math.floor(Math.random() * 1000);

// Hàm tạo ngày trong tương lai
const getFutureDate = (daysAdd) => {
  const date = new Date();
  date.setDate(date.getDate() + daysAdd);
  return date;
};


// Dữ liệu mẫu đầy đủ (20 tours)
const sampleTours = [
  // --- TRONG NƯỚC (10 Tours) ---
  {
    tourName: "Phú Quốc - Thiên đường nghỉ dưỡng 5 sao 3N2Đ",
    destination: "Phú Quốc",
    departure: "TP. Hồ Chí Minh",
    price: 8500000,
    category: "domestic",
    region: "mien-nam",
    country: "Việt Nam",
    tourType: "beach",
    itinerary: "Ngày 1: Đón sân bay, check-in resort 5 sao view biển. Thưởng thức cocktail ngắm hoàng hôn tại Sunset Sanato. Ngày 2: Trải nghiệm cano 4 đảo, lặn ngắm san hô tại Hòn Móng Tay. Tối thưởng thức hải sản tươi sống tại chợ đêm. Ngày 3: Tự do tắm biển bãi Sao, mua sắm ngọc trai và nước mắm truyền thống.",
    highlights: ["Nghỉ dưỡng resort 5 sao sang trọng", "Lặn ngắm san hô rực rỡ", "Ngắm hoàng hôn đẹp nhất Việt Nam", "Ẩm thực hải sản tươi ngon"],
    duration: 3,
    transportation: "Máy bay, Xe du lịch",
    startDate: getFutureDate(10),
    endDate: getFutureDate(13),
    availableSlots: 10,
    totalSlots: 20,
    services: ["Resort 5 sao", "Buffet sáng", "Xe đưa đón", "Vé tham quan"],
    images: ["/uploads/sample-phuquoc.jpg"],
    included: ["Vé máy bay", "Khách sạn", "Ăn uống"],
    excluded: ["Chi phí cá nhân"],
    difficulty: "easy",
    featured: true
  },
  {
    tourName: "Hà Giang - Chinh phục cao nguyên đá hùng vĩ 3N2Đ",
    destination: "Hà Giang",
    departure: "Hà Nội",
    price: 2800000,
    category: "domestic",
    region: "mien-bac",
    country: "Việt Nam",
    tourType: "adventure",
    itinerary: "Ngày 1: Hà Nội - Hà Giang. Check-in cột mốc số 0. Khám phá Cổng trời Quản Bạ và Núi Đôi cô tiên. Ngày 2: Chinh phục đèo Mã Pí Lèng - tứ đại đỉnh đèo. Đi thuyền trên sông Nho Quế ngắm hẻm Tu Sản xanh biếc. Thăm cột cờ Lũng Cú. Ngày 3: Dạo chơi Phố cổ Đồng Văn, thưởng thức cafe phố cổ, thăm Dinh Vua Mèo.",
    highlights: ["Chinh phục đèo Mã Pí Lèng hiểm trở", "Đi thuyền sông Nho Quế thơ mộng", "Check-in cột cờ Lũng Cú thiêng liêng", "Văn hóa bản địa vùng cao độc đáo"],
    duration: 3,
    transportation: "Xe giường nằm, Xe máy",
    startDate: getFutureDate(5),
    endDate: getFutureDate(8),
    availableSlots: 5,
    totalSlots: 15,
    services: ["Homestay bản địa", "Xe máy", "Hướng dẫn viên"],
    images: ["/uploads/sample-hagiang.jpg"],
    included: ["Xe di chuyển", "Homestay", "Các bữa ăn chính"],
    excluded: ["Đồ uống"],
    difficulty: "moderate",
    featured: true
  },
  {
    tourName: "Đà Lạt - Thành phố ngàn hoa lãng mạn 3N2Đ",
    destination: "Đà Lạt",
    departure: "TP. Hồ Chí Minh",
    price: 2200000,
    category: "domestic",
    region: "mien-trung",
    country: "Việt Nam",
    tourType: "nature",
    itinerary: "Ngày 1: Khám phá Quảng trường Lâm Viên, Hồ Xuân Hương. Tối thưởng thức lẩu gà lá é trong không khí se lạnh. Ngày 2: Săn mây tại đồi chè Cầu Đất. Tham quan vườn hoa Cẩm Tú Cầu, Thung lũng Tình Yêu. Tối giao lưu cồng chiêng Langbiang. Ngày 3: Check-in ga Đà Lạt cổ kính, mua dâu tây tại vườn.",
    highlights: ["Không khí se lạnh lãng mạn", "Săn mây sáng sớm", "Check-in các điểm sống ảo cực chill", "Thưởng thức ẩm thực phố núi"],
    duration: 3,
    transportation: "Xe Limousine",
    startDate: getFutureDate(7),
    endDate: getFutureDate(10),
    availableSlots: 8,
    totalSlots: 20,
    services: ["Khách sạn 3 sao", "Xe đưa đón", "BBQ tối"],
    images: ["/uploads/sample-dalat.jpg"],
    included: ["Xe", "Khách sạn", "Vé tham quan"],
    excluded: ["Chi phí mua sắm"],
    difficulty: "easy",
    featured: false
  },
  {
    tourName: "Huế - Đà Nẵng - Hội An: Con đường di sản 4N3Đ",
    destination: "Đà Nẵng",
    departure: "Hà Nội",
    price: 4500000,
    category: "domestic",
    region: "mien-trung",
    country: "Việt Nam",
    tourType: "cultural",
    itinerary: "Ngày 1: Tham quan Đại Nội Huế, lăng tẩm vua chúa triều Nguyễn uy nghiêm. Ngày 2: Vượt đèo Hải Vân đến Đà Nẵng. Tham quan Bán đảo Sơn Trà, chùa Linh Ứng. Ngày 3: Vui chơi tại Bà Nà Hills, check-in Cầu Vàng. Tối dạo phố cổ Hội An thả đèn hoa đăng lung linh. Ngày 4: Tắm biển Mỹ Khê, mua sắm đặc sản.",
    highlights: ["Khám phá di sản văn hóa thế giới", "Check-in Cầu Vàng bàn tay khổng lồ", "Phố cổ Hội An lung linh đèn lồng", "Ẩm thực miền Trung đa dạng"],
    duration: 4,
    transportation: "Máy bay, Ô tô",
    startDate: getFutureDate(15),
    endDate: getFutureDate(19),
    availableSlots: 12,
    totalSlots: 25,
    services: ["Khách sạn 4 sao", "Vé Bà Nà Hills", "Buffet"],
    images: ["/uploads/sample-danang.jpg"],
    included: ["Vé máy bay", "Khách sạn", "Ăn uống"],
    excluded: ["Vé cáp treo tự túc"],
    difficulty: "easy",
    featured: true
  },
  {
    tourName: "Ninh Bình - Tràng An - Bái Đính 1 ngày",
    destination: "Ninh Bình",
    departure: "Hà Nội",
    price: 950000,
    category: "domestic",
    region: "mien-bac",
    country: "Việt Nam",
    tourType: "nature",
    itinerary: "Sáng: Tham quan chùa Bái Đính - ngôi chùa có tượng Phật bằng đồng lớn nhất Đông Nam Á. Chiều: Ngồi thuyền khám phá khu du lịch sinh thái Tràng An, đi qua các hang động đá vôi huyền bí và phim trường Kong: Skull Island.",
    highlights: ["Ngồi thuyền ngắm non nước hữu tình", "Chiêm bái ngôi chùa kỷ lục Châu Á", "Khám phá hang động tự nhiên", "Thưởng thức đặc sản thịt dê cơm cháy"],
    duration: 1,
    transportation: "Ô tô",
    startDate: getFutureDate(2),
    endDate: getFutureDate(2),
    availableSlots: 20,
    totalSlots: 40,
    services: ["Xe đưa đón", "Vé thắng cảnh", "Thuyền đò"],
    images: ["/uploads/sample-ninhbinh.jpg"],
    included: ["Xe", "Ăn trưa", "Vé tham quan"],
    excluded: ["Xe điện chùa Bái Đính"],
    difficulty: "easy",
    featured: false
  },
  {
    tourName: "Quy Nhơn - Phú Yên: Hoa vàng trên cỏ xanh 3N2Đ",
    destination: "Quy Nhơn",
    departure: "TP. Hồ Chí Minh",
    price: 3200000,
    category: "domestic",
    region: "mien-trung",
    country: "Việt Nam",
    tourType: "beach",
    itinerary: "Ngày 1: Tham quan Eo Gió - nơi ngắm bình minh đẹp nhất Việt Nam, tịnh xá Ngọc Hòa. Ngày 2: Khám phá Kỳ Co với làn nước trong vắt 2 màu. Di chuyển sang Phú Yên thăm Gành Đá Đĩa - tuyệt tác của thiên nhiên. Ngày 3: Check-in Bãi Xép (phim trường Hoa vàng trên cỏ xanh), tháp Nghinh Phong.",
    highlights: ["Bãi biển Kỳ Co hoang sơ tuyệt đẹp", "Gành Đá Đĩa độc đáo nhất thế giới", "Check-in Eo Gió hùng vĩ", "Hải sản tươi ngon giá rẻ"],
    duration: 3,
    transportation: "Tàu hỏa, Ô tô",
    startDate: getFutureDate(12),
    endDate: getFutureDate(15),
    availableSlots: 6,
    totalSlots: 20,
    services: ["Khách sạn ven biển", "Cano ra đảo", "Hải sản"],
    images: ["/uploads/sample-quynhon.jpg"],
    included: ["Vé tàu", "Khách sạn", "Ăn uống"],
    excluded: ["Bia rượu"],
    difficulty: "easy",
    featured: false
  },
  {
    tourName: "Miền Tây - Chợ nổi Cái Răng - Miệt vườn 2N1Đ",
    destination: "Cần Thơ",
    departure: "TP. Hồ Chí Minh",
    price: 1800000,
    category: "domestic",
    region: "mien-nam",
    country: "Việt Nam",
    tourType: "cultural",
    itinerary: "Ngày 1: Sài Gòn - Mỹ Tho. Đi thuyền trên sông Tiền, thăm cù lao Thới Sơn, thưởng thức trái cây miệt vườn, nghe đờn ca tài tử. Ngày 2: Đi chợ nổi Cái Răng từ sáng sớm, trải nghiệm văn hóa sông nước, thưởng thức hủ tiếu lắc trên ghe. Tham quan lò hủ tiếu truyền thống.",
    highlights: ["Trải nghiệm văn hóa chợ nổi độc đáo", "Thưởng thức trái cây tại vườn", "Nghe đờn ca tài tử Nam Bộ", "Đi xuồng ba lá len lỏi rạch dừa"],
    duration: 2,
    transportation: "Ô tô, Thuyền",
    startDate: getFutureDate(3),
    endDate: getFutureDate(5),
    availableSlots: 15,
    totalSlots: 30,
    services: ["Khách sạn", "Thuyền tham quan", "Trái cây"],
    images: ["/uploads/sample-mientay.jpg"],
    included: ["Xe", "Khách sạn", "Vé tham quan"],
    excluded: ["Tip cho lái tàu"],
    difficulty: "easy",
    featured: false
  },
  {
    tourName: "Sapa - Trekking bản Cát Cát - Fansipan 3N2Đ",
    destination: "Sapa",
    departure: "Hà Nội",
    price: 2600000,
    category: "domestic",
    region: "mien-bac",
    country: "Việt Nam",
    tourType: "adventure",
    itinerary: "Ngày 1: Trekking xuống bản Cát Cát, tìm hiểu văn hóa người H'Mông. Ngày 2: Chinh phục đỉnh Fansipan - Nóc nhà Đông Dương bằng cáp treo hiện đại. Săn mây trên đỉnh núi. Ngày 3: Thăm thác Bạc, cổng trời Ô Quy Hồ, thưởng thức đồ nướng Sapa.",
    highlights: ["Chinh phục đỉnh Fansipan hùng vĩ", "Tìm hiểu văn hóa các dân tộc thiểu số", "Trekking bản làng yên bình", "Thưởng thức đồ nướng trong sương mù"],
    duration: 3,
    transportation: "Xe giường nằm",
    startDate: getFutureDate(8),
    endDate: getFutureDate(11),
    availableSlots: 10,
    totalSlots: 20,
    services: ["Khách sạn 3 sao", "Vé cáp treo", "Xe đưa đón"],
    images: ["/uploads/sample-sapa.jpg"],
    included: ["Xe", "Khách sạn", "Ăn sáng"],
    excluded: ["Vé Fansipan (tự túc)"],
    difficulty: "moderate",
    featured: true
  },
  {
    tourName: "Côn Đảo - Về nguồn tâm linh & Biển xanh 3N2Đ",
    destination: "Côn Đảo",
    departure: "TP. Hồ Chí Minh",
    price: 6500000,
    category: "domestic",
    region: "mien-nam",
    country: "Việt Nam",
    tourType: "cultural",
    itinerary: "Ngày 1: Viếng nghĩa trang Hàng Dương, mộ cô Sáu linh thiêng vào đêm. Ngày 2: Tham quan hệ thống nhà tù Côn Đảo - địa ngục trần gian. Tắm biển bãi Đầm Trầu hoang sơ, ngắm máy bay hạ cánh sát đầu. Ngày 3: Viếng miếu bà Phi Yến, chùa Núi Một.",
    highlights: ["Du lịch tâm linh linh thiêng", "Tìm hiểu lịch sử hào hùng", "Bãi biển hoang sơ trong vắt", "Không gian yên bình tĩnh lặng"],
    duration: 3,
    transportation: "Máy bay, Tàu cao tốc",
    startDate: getFutureDate(20),
    endDate: getFutureDate(23),
    availableSlots: 5,
    totalSlots: 15,
    services: ["Khách sạn", "Đồ lễ", "Xe đưa đón"],
    images: ["/uploads/sample-condao.jpg"],
    included: ["Vé máy bay", "Khách sạn", "Ăn uống"],
    excluded: ["Đồ cúng"],
    difficulty: "easy",
    featured: false
  },
  {
    tourName: "Mộc Châu - Mùa hoa mận trắng 2N1Đ",
    destination: "Mộc Châu",
    departure: "Hà Nội",
    price: 1500000,
    category: "domestic",
    region: "mien-bac",
    country: "Việt Nam",
    tourType: "nature",
    itinerary: "Ngày 1: Tham quan đồi chè Trái Tim xanh mướt. Chụp ảnh tại thung lũng mận Nà Ka trắng xóa hoa mận. Ngày 2: Khám phá thác Dải Yếm, cầu kính Tình Yêu. Tham quan rừng thông Bản Áng thơ mộng như Đà Lạt thu nhỏ.",
    highlights: ["Ngắm hoa mận nở trắng rừng", "Check-in đồi chè xanh ngát", "Trải nghiệm cầu kính cảm giác mạnh", "Không khí trong lành mát mẻ"],
    duration: 2,
    transportation: "Xe Limousine",
    startDate: getFutureDate(6),
    endDate: getFutureDate(8),
    availableSlots: 12,
    totalSlots: 20,
    services: ["Homestay", "Xe đưa đón", "Lửa trại"],
    images: ["/uploads/sample-mocchau.jpg"],
    included: ["Xe", "Homestay", "Ăn uống"],
    excluded: ["Vé cầu kính"],
    difficulty: "easy",
    featured: false
  },

  // --- QUỐC TẾ (10 Tours) ---
  {
    tourName: "Thái Lan - Bangkok - Pattaya sôi động 5N4Đ",
    destination: "Thái Lan",
    departure: "TP. Hồ Chí Minh",
    price: 7500000,
    category: "international",
    region: "dong-nam-a",
    country: "Thái Lan",
    tourType: "city",
    itinerary: "Ngày 1: Khám phá Bangkok, dạo thuyền sông Chaophraya. Ngày 2: Di chuyển đi Pattaya, tham quan chợ nổi 4 miền. Tối xem Alcazar Show hoành tráng. Ngày 3: Tắm biển đảo Coral, tham quan vườn nhiệt đới Nong Nooch. Ngày 4: Viếng chùa Phật Vàng, tự do mua sắm tại Big C, Central World. Ngày 5: Bái Phật 4 Mặt linh thiêng.",
    highlights: ["Thiên đường mua sắm giá rẻ", "Show diễn chuyển giới hoành tráng", "Văn hóa chùa chiền độc đáo", "Ẩm thực đường phố phong phú"],
    duration: 5,
    transportation: "Máy bay",
    startDate: getFutureDate(15),
    endDate: getFutureDate(20),
    availableSlots: 15,
    totalSlots: 30,
    services: ["Khách sạn 4 sao", "Vé máy bay", "Xe đưa đón"],
    images: ["/uploads/sample-thailand.jpg"],
    included: ["Vé máy bay", "Khách sạn", "Ăn uống"],
    excluded: ["Tiền tip HDV"],
    difficulty: "easy",
    featured: true
  },
  {
    tourName: "Hàn Quốc - Mùa thu lá đỏ Seoul - Nami 5N4Đ",
    destination: "Hàn Quốc",
    departure: "Hà Nội",
    price: 16900000,
    category: "international",
    region: "dong-a",
    country: "Hàn Quốc",
    tourType: "nature",
    itinerary: "Ngày 1: Bay đến Seoul. Ngày 2: Tham quan đảo Nami - phim trường Bản Tình Ca Mùa Đông lãng mạn với hàng cây lá vàng. Ngày 3: Cung điện Gyeongbokgung, làng cổ Bukchon Hanok, tháp Namsan. Ngày 4: Vui chơi tại công viên Everland, trải nghiệm làm kim chi, mặc Hanbok. Ngày 5: Mua sắm mỹ phẩm, nhân sâm.",
    highlights: ["Ngắm lá vàng lá đỏ lãng mạn", "Trải nghiệm mặc Hanbok truyền thống", "Check-in các điểm quay phim nổi tiếng", "Thưởng thức thịt nướng Hàn Quốc"],
    duration: 5,
    transportation: "Máy bay",
    startDate: getFutureDate(30),
    endDate: getFutureDate(35),
    availableSlots: 8,
    totalSlots: 20,
    services: ["Visa", "Khách sạn 4 sao", "Vé Everland"],
    images: ["/uploads/sample-korea.jpg"],
    included: ["Visa", "Vé máy bay", "Khách sạn"],
    excluded: ["Chi phí cá nhân"],
    difficulty: "easy",
    featured: true
  },
  {
    tourName: "Nhật Bản - Cung đường vàng Tokyo - Kyoto - Osaka 6N5Đ",
    destination: "Nhật Bản",
    departure: "TP. Hồ Chí Minh",
    price: 29900000,
    category: "international",
    region: "dong-a",
    country: "Nhật Bản",
    tourType: "cultural",
    itinerary: "Ngày 1: Tokyo - Chùa Asakusa, tháp Tokyo Skytree. Ngày 2: Núi Phú Sĩ, làng cổ Oshino Hakkai, tắm Onsen truyền thống. Ngày 3: Trải nghiệm tàu Shinkansen đi Kyoto, thăm Chùa Vàng, rừng tre Arashiyama. Ngày 4: Osaka - Lâu đài Osaka, mua sắm tại Shinsaibashi. Ngày 5: Công viên Nara chơi với hươu sao.",
    highlights: ["Ngắm núi Phú Sĩ biểu tượng", "Trải nghiệm tàu cao tốc Shinkansen", "Văn hóa trà đạo và tắm Onsen", "Kiến trúc đền đài cổ kính"],
    duration: 6,
    transportation: "Máy bay, Tàu Shinkansen",
    startDate: getFutureDate(40),
    endDate: getFutureDate(46),
    availableSlots: 5,
    totalSlots: 25,
    services: ["Visa", "Khách sạn 3-4 sao", "Vé tàu"],
    images: ["/uploads/sample-japan.jpg"],
    included: ["Visa", "Vé máy bay", "Ăn uống"],
    excluded: ["Mua sắm"],
    difficulty: "moderate",
    featured: true
  },
  {
    tourName: "Singapore - Đảo quốc Sư Tử hiện đại 4N3Đ",
    destination: "Singapore",
    departure: "TP. Hồ Chí Minh",
    price: 11500000,
    category: "international",
    region: "dong-nam-a",
    country: "Singapore",
    tourType: "city",
    itinerary: "Ngày 1: Check-in sân bay Changi đẹp nhất thế giới (Jewel). Tham quan công viên Sư Tử Biển. Ngày 2: Khám phá Gardens by the Bay với các siêu cây khổng lồ, Flower Dome. Tối xem nhạc nước Spectra. Ngày 3: Vui chơi tại đảo Sentosa, Universal Studios (tự túc), tham quan S.E.A Aquarium. Ngày 4: Mua sắm tại Orchard Road.",
    highlights: ["Thành phố xanh sạch hiện đại nhất", "Gardens by the Bay kỳ vĩ", "Khu vui chơi giải trí hàng đầu Sentosa", "Thiên đường mua sắm hàng hiệu"],
    duration: 4,
    transportation: "Máy bay",
    startDate: getFutureDate(18),
    endDate: getFutureDate(22),
    availableSlots: 10,
    totalSlots: 20,
    services: ["Khách sạn 3 sao", "Vé tham quan", "Xe đưa đón"],
    images: ["/uploads/sample-singapore.jpg"],
    included: ["Vé máy bay", "Khách sạn", "Ăn sáng"],
    excluded: ["Vé Universal Studios"],
    difficulty: "easy",
    featured: false
  },
  {
    tourName: "Bali - Thiên đường nhiệt đới vạn người mê 4N3Đ",
    destination: "Indonesia",
    departure: "TP. Hồ Chí Minh",
    price: 9900000,
    category: "international",
    region: "dong-nam-a",
    country: "Indonesia",
    tourType: "beach",
    itinerary: "Ngày 1: Đền Uluwatu trên vách đá, ngắm hoàng hôn biển Ấn Độ Dương. Ngày 2: Đảo Nusa Penida - Check-in sống lưng khủng long Kelingking Beach, Angel's Billabong. Ngày 3: Cổng trời Lempuyang, Cung điện nước Tirta Gangga, Xích đu Bali Swing giữa ruộng bậc thang. Ngày 4: Tự do nghỉ dưỡng resort.",
    highlights: ["Check-in sống lưng khủng long huyền thoại", "Cổng trời Bali linh thiêng", "Văn hóa Hindu giáo độc đáo", "Nghỉ dưỡng phong cách nhiệt đới"],
    duration: 4,
    transportation: "Máy bay",
    startDate: getFutureDate(25),
    endDate: getFutureDate(29),
    availableSlots: 8,
    totalSlots: 20,
    services: ["Resort", "Tàu cao tốc", "Xe đưa đón"],
    images: ["/uploads/sample-bali.jpg"],
    included: ["Vé máy bay", "Khách sạn", "Ăn uống"],
    excluded: ["Chi phí chụp ảnh"],
    difficulty: "moderate",
    featured: false
  },
  {
    tourName: "Phượng Hoàng Cổ Trấn - Trương Gia Giới 5N4Đ",
    destination: "Trung Quốc",
    departure: "Hà Nội",
    price: 8900000,
    category: "international",
    region: "dong-a",
    country: "Trung Quốc",
    tourType: "nature",
    itinerary: "Ngày 1: Đến Trương Gia Giới. Ngày 2: Thiên Môn Sơn - Trải nghiệm cáp treo dài nhất thế giới, đi trên con đường vách kính (Sàn Đạo Kính). Ngày 3: Di chuyển đến Phượng Hoàng Cổ Trấn - ngắm cảnh đêm lung linh bên dòng Đà Giang. Ngày 4: Dạo chơi phố cổ ban ngày, cầu Hồng Kiều. Ngày 5: Mua sắm và trở về.",
    highlights: ["Phố cổ ngàn năm tuổi đẹp như tranh", "Cảnh sắc núi non hùng vĩ như phim Avatar", "Trải nghiệm văn hóa Trung Hoa", "Cáp treo vượt núi ngoạn mục"],
    duration: 5,
    transportation: "Máy bay, Ô tô",
    startDate: getFutureDate(45),
    endDate: getFutureDate(50),
    availableSlots: 20,
    totalSlots: 30,
    services: ["Visa đoàn", "Khách sạn 4 sao", "Vé tham quan"],
    images: ["/uploads/sample-china.jpg"],
    included: ["Visa", "Vé máy bay", "Khách sạn"],
    excluded: ["Show diễn"],
    difficulty: "easy",
    featured: true
  },
  {
    tourName: "Châu Âu: Pháp - Thụy Sĩ - Ý lãng mạn 10N9Đ",
    destination: "Châu Âu",
    departure: "TP. Hồ Chí Minh",
    price: 55000000,
    category: "international",
    region: "chau-au",
    country: "Pháp, Thụy Sĩ, Ý",
    tourType: "cultural",
    itinerary: "Ngày 1-3: Paris (Pháp) - Tháp Eiffel, bảo tàng Louvre, du thuyền sông Seine, Khải Hoàn Môn. Ngày 4-6: Thụy Sĩ - Núi tuyết Titlis, thành phố Lucerne yên bình, làng cổ tích. Ngày 7-9: Ý - Venice thành phố tình yêu, tháp nghiêng Pisa, đấu trường La Mã Colosseum ở Rome. Ngày 10: Vatican và bay về.",
    highlights: ["Hành trình qua 3 nước đẹp nhất Châu Âu", "Chiêm ngưỡng tháp Eiffel và tháp nghiêng Pisa", "Trải nghiệm tuyết vĩnh cửu tại Thụy Sĩ", "Đi thuyền Gondola lãng mạn tại Venice"],
    duration: 10,
    transportation: "Máy bay",
    startDate: getFutureDate(60),
    endDate: getFutureDate(70),
    availableSlots: 10,
    totalSlots: 20,
    services: ["Visa Schengen", "Khách sạn 4-5 sao", "Xe Châu Âu"],
    images: ["/uploads/sample-europe.jpg"],
    included: ["Visa", "Vé máy bay", "Khách sạn"],
    excluded: ["Tiền tip bắt buộc"],
    difficulty: "moderate",
    featured: true
  },
  {
    tourName: "Dubai - Sa mạc huyền bí & Sự xa hoa tột bậc 5N4Đ",
    destination: "Dubai",
    departure: "Hà Nội",
    price: 22000000,
    category: "international",
    region: "other",
    country: "UAE",
    tourType: "adventure", // Sử dụng tourType adventure cho hoạt động sa mạc
    itinerary: "Ngày 1: Tham quan Đảo Cọ (Palm Jumeirah), khách sạn 7 sao Burj Al Arab. Ngày 2: Chinh phục tháp Burj Khalifa cao nhất thế giới, xem nhạc nước, mua sắm Dubai Mall. Ngày 3: Sa mạc Safari - Đua xe Land Cruiser trên cát, cưỡi lạc đà, múa bụng Belly Dance, ăn tối BBQ. Ngày 4: Vườn hoa Miracle Garden, Chợ Vàng Gold Souk. Ngày 5: Tự do và bay về.",
    highlights: ["Trải nghiệm sự xa hoa bậc nhất thế giới", "Đua xe cảm giác mạnh trên sa mạc", "Ngắm toàn cảnh từ tòa nhà cao nhất thế giới", "Mua sắm vàng và hàng hiệu"],
    duration: 5,
    transportation: "Máy bay",
    startDate: getFutureDate(35),
    endDate: getFutureDate(40),
    availableSlots: 12,
    totalSlots: 25,
    services: ["Visa", "Khách sạn 5 sao", "Xe Jeep sa mạc"],
    images: ["/uploads/sample-dubai.jpg"],
    included: ["Visa", "Vé máy bay", "Khách sạn"],
    excluded: ["Mua sắm cá nhân"],
    difficulty: "easy",
    featured: true
  },
  {
    tourName: "Đài Loan - Trà sữa & Chợ đêm 5N4Đ",
    destination: "Đài Loan",
    departure: "TP. Hồ Chí Minh",
    price: 10500000,
    category: "international",
    region: "dong-a",
    country: "Đài Loan",
    tourType: "city",
    itinerary: "Ngày 1: Cao Hùng - Phật Quang Sơn, Đầm Liên Trì. Chợ đêm Lục Hợp. Ngày 2: Đài Trung - Hồ Nhật Nguyệt thơ mộng, Văn Võ Miếu. Ngày 3: Làng Cầu Vồng, Nhà hát Opera. Ngày 4: Đài Bắc - Phố cổ Cửu Phần (như phim Spirited Away), thả đèn trời Thập Phần, tháp Taipei 101. Ngày 5: Học làm bánh dứa và bay về.",
    highlights: ["Thiên đường ẩm thực chợ đêm", "Phố cổ Cửu Phần lung linh đèn lồng", "Thả đèn trời cầu may mắn", "Thưởng thức trà sữa chính gốc"],
    duration: 5,
    transportation: "Máy bay",
    startDate: getFutureDate(20),
    endDate: getFutureDate(25),
    availableSlots: 15,
    totalSlots: 30,
    services: ["Visa Quan Hồng", "Khách sạn 3 sao", "Xe đưa đón"],
    images: ["/uploads/sample-taiwan.jpg"],
    included: ["Visa", "Vé máy bay", "Khách sạn"],
    excluded: ["Chi phí cá nhân"],
    difficulty: "easy",
    featured: false
  },
  {
    tourName: "Úc - Sydney - Melbourne mùa xuân 6N5Đ",
    destination: "Úc",
    departure: "TP. Hồ Chí Minh",
    price: 35000000,
    category: "international",
    region: "chau-uc",
    country: "Úc",
    tourType: "nature",
    itinerary: "Ngày 1-3: Sydney - Nhà hát Con Sò (Opera House), Cầu cảng Sydney, bãi biển Bondi, vườn thú Taronga ngắm Kangaroo và Koala. Ngày 4-6: Melbourne - Con đường đại dương Great Ocean Road, đi tàu hơi nước Puffing Billy, quảng trường Federation. Mua sắm tại chợ Queen Victoria.",
    highlights: ["Check-in Nhà hát Con Sò biểu tượng", "Gặp gỡ Kangaroo và Gấu túi Koala", "Thiên nhiên hùng vĩ tại Great Ocean Road", "Thành phố đáng sống nhất thế giới"],
    duration: 6,
    transportation: "Máy bay",
    startDate: getFutureDate(50),
    endDate: getFutureDate(56),
    availableSlots: 8,
    totalSlots: 20,
    services: ["Visa Úc", "Khách sạn 4 sao", "Xe tham quan"],
    images: ["/uploads/sample-australia.jpg"],
    included: ["Visa", "Vé máy bay", "Khách sạn"],
    excluded: ["Tip cho tài xế"],
    difficulty: "easy",
    featured: true
  }

  // --- BỔ SUNG: CÙNG ĐỊA ĐIỂM NHƯNG KHÁC TRẢI NGHIỆM ---

  // 1. Hạ Long - Thay vì ngủ du thuyền, đây là tour Adventure leo núi đảo Cát Bà
  // {
  //   tourName: "Cát Bà - Vịnh Lan Hạ - Trekking Vườn Quốc Gia 2N1Đ",
  //   destination: "Hạ Long", // Vẫn chung vùng Hạ Long/Quảng Ninh để test
  //   departure: "Hà Nội",
  //   price: 1800000,
  //   category: "domestic",
  //   region: "mien-bac",
  //   country: "Việt Nam",
  //   tourType: "adventure", // Khác tour cũ (luxury)
  //   itinerary: "Ngày 1: Hà Nội - Cát Bà. Trekking xuyên rừng quốc gia Cát Bà, chinh phục đỉnh Ngự Lâm ngắm toàn cảnh đảo. Tối ngủ Bungalow. Ngày 2: Chèo Kayak khám phá Vịnh Lan Hạ hoang sơ, tắm biển tại Đảo Khỉ, thăm làng chài Cái Bèo cổ nhất Việt Nam.",
  //   highlights: ["Trekking xuyên rừng già", "Chèo Kayak vịnh Lan Hạ", "Khám phá làng chài cổ", "Trải nghiệm thiên nhiên hoang dã"],
  //   duration: 2,
  //   transportation: "Xe buýt, Tàu cao tốc",
  //   startDate: getFutureDate(5),
  //   endDate: getFutureDate(7),
  //   availableSlots: 15,
  //   totalSlots: 25,
  //   services: ["Bungalow", "Kayak", "Xe đưa đón"],
  //   images: ["/uploads/sample-catba.jpg"],
  //   included: ["Xe", "Ăn uống", "Vé thắng cảnh"],
  //   excluded: ["Đồ uống"],
  //   difficulty: "moderate", // Khó hơn tour du thuyền
  //   featured: false
  // },

  // // 2. Sapa - Thay vì leo núi cực khổ, đây là tour nghỉ dưỡng sang chảnh
  // {
  //   tourName: "Sapa Retreat - Nghỉ dưỡng Resort & Tắm lá thuốc 3N2Đ",
  //   destination: "Sapa",
  //   departure: "Hà Nội",
  //   price: 5500000,
  //   category: "domestic",
  //   region: "mien-bac",
  //   country: "Việt Nam",
  //   tourType: "luxury", // Khác tour cũ (adventure)
  //   itinerary: "Ngày 1: Xe Limousine đón đi Sapa. Check-in Topas Ecolodge - resort biệt lập trên đỉnh đồi. Tắm hồ bơi vô cực view ruộng bậc thang. Ngày 2: Thư giãn với liệu trình tắm lá thuốc người Dao Đỏ. Thưởng thức tiệc trà chiều ngắm hoàng hôn thung lũng Mường Hoa. Ngày 3: Tự do nghỉ dưỡng và mua sắm.",
  //   highlights: ["Hồ bơi vô cực view núi đẹp nhất Sapa", "Nghỉ dưỡng biệt lập yên tĩnh", "Liệu pháp tắm lá thuốc cổ truyền", "Dịch vụ 5 sao đẳng cấp"],
  //   duration: 3,
  //   transportation: "Xe Limousine VIP",
  //   startDate: getFutureDate(10),
  //   endDate: getFutureDate(13),
  //   availableSlots: 6,
  //   totalSlots: 12,
  //   services: ["Resort 4-5 sao", "Spa", "Xe VIP"],
  //   images: ["/uploads/sample-sapa-resort.jpg"],
  //   included: ["Xe", "Resort", "Ăn sáng", "Spa"],
  //   excluded: ["Các bữa ăn chính"],
  //   difficulty: "easy",
  //   featured: true
  // },

  // // 3. Đà Lạt - Thay vì đi city tour, đây là tour cắm trại (Camping)
  // {
  //   tourName: "Camping Đà Lạt - Săn mây & Chèo SUP Hồ Tuyền Lâm 2N1Đ",
  //   destination: "Đà Lạt",
  //   departure: "Đà Lạt", // Đón tại Đà Lạt
  //   price: 1500000,
  //   category: "domestic",
  //   region: "mien-trung",
  //   country: "Việt Nam",
  //   tourType: "nature", // Thiên về thiên nhiên/camping
  //   itinerary: "Ngày 1: Chèo SUP đón hoàng hôn trên hồ Tuyền Lâm. Dựng trại ven hồ, tiệc nướng BBQ ngoài trời, đốt lửa trại giao lưu acoustic. Ngày 2: Thức dậy sớm săn mây ngay tại lều. Thưởng thức cafe sáng giữa rừng thông. Thu dọn lều và kết thúc hành trình.",
  //   highlights: ["Chèo SUP hồ Tuyền Lâm", "Cắm trại ngủ lều giữa rừng thông", "Tiệc nướng BBQ và lửa trại", "Săn mây bình minh cực chill"],
  //   duration: 2,
  //   transportation: "Xe máy hoặc Xe địa hình",
  //   startDate: getFutureDate(3),
  //   endDate: getFutureDate(5),
  //   availableSlots: 20,
  //   totalSlots: 30,
  //   services: ["Lều trại cao cấp", "SUP", "BBQ"],
  //   images: ["/uploads/sample-dalat-camp.jpg"],
  //   included: ["Lều", "Ăn tối BBQ", "SUP"],
  //   excluded: ["Xe di chuyển đến điểm trại"],
  //   difficulty: "moderate",
  //   featured: false
  // },

  // // 4. Phú Quốc - Thay vì nghỉ dưỡng 5 sao, đây là tour khám phá đảo hoang (Action)
  // {
  //   tourName: "Phú Quốc - Cano 4 đảo & Cáp treo Hòn Thơm 1 ngày",
  //   destination: "Phú Quốc",
  //   departure: "Phú Quốc",
  //   price: 1200000,
  //   category: "domestic",
  //   region: "mien-nam",
  //   country: "Việt Nam",
  //   tourType: "adventure", // Thiên về hoạt động
  //   itinerary: "Sáng: Cano siêu tốc đưa đoàn đi tham quan 4 đảo đẹp nhất: Hòn Mây Rút, Hòn Gầm Ghì... Trải nghiệm đi bộ dưới đáy biển (Seawalker). Chiều: Đi cáp treo vượt biển dài nhất thế giới sang Hòn Thơm. Vui chơi tại công viên nước Aquatopia.",
  //   highlights: ["Cano siêu tốc cảm giác mạnh", "Cáp treo vượt biển kỷ lục thế giới", "Check-in các hòn đảo hoang sơ", "Công viên nước quy mô lớn"],
  //   duration: 1,
  //   transportation: "Cano, Cáp treo",
  //   startDate: getFutureDate(2),
  //   endDate: getFutureDate(2),
  //   availableSlots: 30,
  //   totalSlots: 50,
  //   services: ["Cano", "Vé cáp treo", "Ăn trưa"],
  //   images: ["/uploads/sample-phuquoc-cano.jpg"],
  //   included: ["Vé tham quan", "Ăn trưa", "Đưa đón"],
  //   excluded: ["Vé đi bộ dưới biển"],
  //   difficulty: "moderate",
  //   featured: false
  // },

  // // 5. Ninh Bình - Thay vì đi thuyền nhẹ nhàng, đây là Trekking rừng
  // {
  //   tourName: "Vườn Quốc Gia Cúc Phương - Mùa bướm bay 2N1Đ",
  //   destination: "Ninh Bình",
  //   departure: "Hà Nội",
  //   price: 2100000,
  //   category: "domestic",
  //   region: "mien-bac",
  //   country: "Việt Nam",
  //   tourType: "nature", // Thiên về khám phá sinh thái
  //   itinerary: "Ngày 1: Tham quan Trung tâm cứu hộ linh trưởng. Trekking vào rừng già thăm Cây Chò ngàn năm. Tối soi thú đêm. Ngày 2: Chụp ảnh mùa bướm rừng Cúc Phương rợp trời. Thăm Động Người Xưa. Tìm hiểu hệ sinh thái rừng nhiệt đới.",
  //   highlights: ["Mùa bướm bay rợp trời (theo mùa)", "Trekking rừng nguyên sinh", "Trải nghiệm soi thú đêm độc đáo", "Giáo dục bảo tồn thiên nhiên"],
  //   duration: 2,
  //   transportation: "Ô tô",
  //   startDate: getFutureDate(12),
  //   endDate: getFutureDate(14),
  //   availableSlots: 15,
  //   totalSlots: 25,
  //   services: ["Nhà sàn", "Hướng dẫn viên sinh thái"],
  //   images: ["/uploads/sample-cucphuong.jpg"],
  //   included: ["Xe", "Lưu trú", "Vé rừng"],
  //   excluded: ["Tip"],
  //   difficulty: "moderate",
  //   featured: false
  // },

  // // 6. Miền Tây - Thay vì Cần Thơ, đi An Giang mùa nước nổi
  // {
  //   tourName: "An Giang - Rừng tràm Trà Sư Mùa nước nổi 2N1Đ",
  //   destination: "Châu Đốc", // Cùng vùng Miền Tây với Cần Thơ
  //   departure: "TP. Hồ Chí Minh",
  //   price: 1900000,
  //   category: "domestic",
  //   region: "mien-nam",
  //   country: "Việt Nam",
  //   tourType: "nature",
  //   itinerary: "Ngày 1: Viếng Miếu Bà Chúa Xứ linh thiêng. Check-in Rừng tràm Trà Sư với thảm bèo xanh mướt, đi xuồng máy len lỏi giữa rừng. Ngày 2: Tham quan Làng văn hóa người Chăm, thánh đường Hồi giáo Mubarak. Mua sắm đặc sản mắm Châu Đốc.",
  //   highlights: ["Rừng tràm đẹp nhất Việt Nam", "Văn hóa tâm linh Miếu Bà", "Đời sống người Chăm độc đáo", "Đặc sản thốt nốt, mắm"],
  //   duration: 2,
  //   transportation: "Xe giường nằm",
  //   startDate: getFutureDate(8),
  //   endDate: getFutureDate(10),
  //   availableSlots: 20,
  //   totalSlots: 40,
  //   services: ["Khách sạn 3 sao", "Xuồng máy", "Xe"],
  //   images: ["/uploads/sample-angiang.jpg"],
  //   included: ["Xe", "Khách sạn", "Ăn uống"],
  //   excluded: ["Mua sắm"],
  //   difficulty: "easy",
  //   featured: true
  // },

  // // 7. Hội An - Thay vì phố cổ, đi làm nông dân/ngư dân
  // {
  //   tourName: "Hội An - Làm nông dân Trà Quế & Rừng dừa Bảy Mẫu 1 ngày",
  //   destination: "Hội An", // Cùng cụm Đà Nẵng - Hội An
  //   departure: "Đà Nẵng",
  //   price: 850000,
  //   category: "domestic",
  //   region: "mien-trung",
  //   country: "Việt Nam",
  //   tourType: "cultural", // Thiên về trải nghiệm thực tế
  //   itinerary: "Sáng: Đạp xe đến làng rau Trà Quế, mặc áo nâu tập làm nông dân, cưỡi trâu. Chiều: Đến rừng dừa Bảy Mẫu, ngồi thuyền thúng xem múa thúng, tập quăng chài bắt cá. Thưởng thức món cao lầu đặc sản.",
  //   highlights: ["Trải nghiệm làm nông dân thực thụ", "Múa thúng cảm giác mạnh tại rừng dừa", "Không khí làng quê yên bình", "Ẩm thực dân dã"],
  //   duration: 1,
  //   transportation: "Xe đạp, Thuyền thúng",
  //   startDate: getFutureDate(1),
  //   endDate: getFutureDate(1),
  //   availableSlots: 10,
  //   totalSlots: 20,
  //   services: ["Xe đạp", "Thuyền thúng", "Ăn trưa"],
  //   images: ["/uploads/sample-hoian-eco.jpg"],
  //   included: ["Vé tham quan", "Ăn trưa", "Dụng cụ"],
  //   excluded: ["Tiền tip người chèo thúng"],
  //   difficulty: "easy",
  //   featured: false
  // },

  // // 8. Hà Giang - Thay vì đi phượt xe máy, đi tour văn hóa nhẹ nhàng
  // {
  //   tourName: "Hà Giang - Mùa hoa Tam Giác Mạch & Làng Lô Lô Chải 3N2Đ",
  //   destination: "Hà Giang",
  //   departure: "Hà Nội",
  //   price: 3200000,
  //   category: "domestic",
  //   region: "mien-bac",
  //   country: "Việt Nam",
  //   tourType: "cultural", // Thiên về văn hóa, check-in
  //   itinerary: "Ngày 1: Check-in các cánh đồng hoa Tam Giác Mạch bạt ngàn. Tối ngủ tại Làng văn hóa Lô Lô Chải ngay dưới chân cột cờ Lũng Cú. Ngày 2: Thưởng thức cafe Cực Bắc, giao lưu văn nghệ với người Lô Lô. Tham quan kiến trúc nhà trình tường. Ngày 3: Mua sắm tại chợ phiên Đồng Văn.",
  //   highlights: ["Sống chậm tại bản làng cổ tích", "Check-in mùa hoa đẹp nhất năm", "Giao lưu văn hóa bản địa sâu sắc", "Không đặt nặng việc di chuyển nhiều"],
  //   duration: 3,
  //   transportation: "Xe 16 chỗ",
  //   startDate: getFutureDate(20),
  //   endDate: getFutureDate(23),
  //   availableSlots: 12,
  //   totalSlots: 18,
  //   services: ["Homestay cao cấp", "Xe đời mới"],
  //   images: ["/uploads/sample-hagiang-flower.jpg"],
  //   included: ["Xe", "Lưu trú", "Ăn uống"],
  //   excluded: ["Trang phục thuê chụp ảnh"],
  //   difficulty: "easy",
  //   featured: true
  // },

  // // 9. Quy Nhơn - Thay vì đi đảo, đi cắm trại Glamping
  // {
  //   tourName: "Quy Nhơn - Glamping Trung Lương & Khu dã ngoại 2N1Đ",
  //   destination: "Quy Nhơn",
  //   departure: "Quy Nhơn",
  //   price: 1600000,
  //   category: "domestic",
  //   region: "mien-trung",
  //   country: "Việt Nam",
  //   tourType: "nature", // Thiên về chill, cắm trại
  //   itinerary: "Ngày 1: Check-in Khu dã ngoại Trung Lương - được mệnh danh là Jeju phiên bản Việt. Tự do tắm biển, chụp ảnh check-in. Tối ngủ lều trại cao cấp (Glamping), tiệc BBQ hải sản. Ngày 2: Đón bình minh trên biển, tham quan chùa Ông Núi có tượng Phật ngồi lớn nhất ĐNA.",
  //   highlights: ["Cắm trại sang chảnh view biển", "Điểm check-in hot nhất Quy Nhơn", "Tiệc nướng hải sản bên bờ biển", "Thích hợp cho cặp đôi"],
  //   duration: 2,
  //   transportation: "Xe đưa đón",
  //   startDate: getFutureDate(5),
  //   endDate: getFutureDate(7),
  //   availableSlots: 10,
  //   totalSlots: 20,
  //   services: ["Lều Glamping", "BBQ"],
  //   images: ["/uploads/sample-quynhon-glamping.jpg"],
  //   included: ["Lều", "Ăn uống", "Vé vào cửa"],
  //   excluded: ["Đồ uống có cồn"],
  //   difficulty: "easy",
  //   featured: false
  // },

  // // 10. Côn Đảo - Thay vì đi lễ Cô Sáu, đi xem rùa đẻ trứng (Mùa hè)
  // {
  //   tourName: "Côn Đảo - Xem rùa đẻ trứng & Khám phá Hòn Bảy Cạnh 2N1Đ",
  //   destination: "Côn Đảo",
  //   departure: "Côn Đảo",
  //   price: 2500000,
  //   category: "domestic",
  //   region: "mien-nam",
  //   country: "Việt Nam",
  //   tourType: "nature", // Tour sinh thái đặc biệt
  //   itinerary: "Ngày 1: Di chuyển cano sang Hòn Bảy Cạnh. Tham quan rừng ngập mặn. Đêm: Lặng lẽ quan sát rùa biển lên bãi cát đẻ trứng (chỉ có vào mùa hè). Ngủ đêm tại trạm kiểm lâm. Ngày 2: Sáng sớm thả rùa con về biển. Lặn ngắm san hô trước khi về lại đảo lớn.",
  //   highlights: ["Trải nghiệm hiếm có xem rùa đẻ trứng", "Thả rùa con về biển", "Hòa mình hoàn toàn vào thiên nhiên", "Lặn ngắm san hô đẹp nhất Côn Đảo"],
  //   duration: 2,
  //   transportation: "Cano",
  //   startDate: getFutureDate(15),
  //   endDate: getFutureDate(17),
  //   availableSlots: 8,
  //   totalSlots: 12,
  //   services: ["Cano", "Phí bảo tồn", "Lưu trú trạm kiểm lâm"],
  //   images: ["/uploads/sample-condao-turtle.jpg"],
  //   included: ["Giấy phép", "Ăn uống", "Cano"],
  //   excluded: ["Tiện nghi cao cấp (ngủ trạm kiểm lâm)"],
  //   difficulty: "moderate",
  //   featured: true
  // }
];

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Kết nối MongoDB thành công!");

    // Chuẩn bị dữ liệu để insert
    const toursWithIds = sampleTours.map(tour => ({
      ...tour,
      tourId: generateTourId(), // Tạo ID
      status: "active",
      rating: 0,
      reviewCount: 0
    }));

    // Insert dữ liệu mới
    await Tour.insertMany(toursWithIds);
    console.log(`Đã thêm thành công ${toursWithIds.length} tour mẫu.`);

    process.exit();
  } catch (error) {
    console.error("Lỗi khi seed data:", error);
    process.exit(1);
  }
};

seedData();